# Generated by Django 5.0.7 on 2024-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_born',
            field=models.DateField(null=True),
        ),
    ]
