# Generated by Django 5.0.7 on 2024-07-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_income_expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance_amount',
            field=models.IntegerField(default=0),
        ),
    ]
